<?php

namespace Database\Seeders;

use App\Models\Emoji;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmojiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $emojis = [
            ['value' => '😀', 'label' => 'Grinning Face'],
            ['value' => '😃', 'label' => 'Grinning Face with Big Eyes'],
            ['value' => '😄', 'label' => 'Grinning Face with Smiling Eyes'],
            ['value' => '😁', 'label' => 'Beaming Face with Smiling Eyes'],
            ['value' => '😆', 'label' => 'Grinning Squinting Face'],
            ['value' => '😅', 'label' => 'Grinning Face with Sweat'],
            ['value' => '😂', 'label' => 'Face with Tears of Joy'],
            ['value' => '🤣', 'label' => 'Rolling on the Floor Laughing'],
            ['value' => '🥲', 'label' => 'Smiling Face with Tear'],
            ['value' => '🥹', 'label' => 'Face Holding Back Tears'],
            ['value' => '☺️', 'label' => 'Smiling Face'],
            ['value' => '😊', 'label' => 'Smiling Face with Smiling Eyes'],
            ['value' => '😇', 'label' => 'Smiling Face with Halo'],
            ['value' => '🙂', 'label' => 'Slightly Smiling Face'],
            ['value' => '🙃', 'label' => 'Upside-Down Face'],
            ['value' => '😉', 'label' => 'Winking Face'],
            ['value' => '😌', 'label' => 'Relieved Face'],
            ['value' => '😍', 'label' => 'Heart Eyes'],
            ['value' => '🥰', 'label' => 'Smiling Face with Hearts'],
            ['value' => '😘', 'label' => 'Face Blowing a Kiss'],
            ['value' => '😗', 'label' => 'Kissing Face'],
            ['value' => '😙', 'label' => 'Kissing Face with Smiling Eyes'],
            ['value' => '😚', 'label' => 'Kissing Face with Closed Eyes'],
            ['value' => '😋', 'label' => 'Face Savoring Food'],
            ['value' => '😛', 'label' => 'Face with Stuck Out Tongue'],
            ['value' => '😝', 'label' => 'Face with Stuck Out Tongue and Tightly Closed Eyes'],
            ['value' => '😜', 'label' => 'Face with Stuck Out Tongue and Winking Eye'],
            ['value' => '🤪', 'label' => 'Zany Face'],
            ['value' => '🤨', 'label' => 'Face with Raised Eyebrow'],
            ['value' => '🧐', 'label' => 'Face with Monocle'],
            ['value' => '🤓', 'label' => 'Nerd Face'],
            ['value' => '😎', 'label' => 'Smiling Face with Sunglasses'],
            ['value' => '🥸', 'label' => 'Disguised Face'],
            ['value' => '🤩', 'label' => 'Star-Struck'],
            ['value' => '🥳', 'label' => 'Partying Face'],
            ['value' => '🙂‍↕️', 'label' => 'Slightly Smiling Face with Arrow Up and Down'],
            ['value' => '😏', 'label' => 'Smirking Face'],
            ['value' => '😒', 'label' => 'Unamused Face'],
            ['value' => '🙂‍↔️', 'label' => 'Slightly Smiling Face with Arrow Left and Right'],
            ['value' => '😞', 'label' => 'Disappointed Face'],
            ['value' => '😔', 'label' => 'Pensive Face'],
            ['value' => '😟', 'label' => 'Worried Face'],
            ['value' => '😕', 'label' => 'Confused Face'],
            ['value' => '🙁', 'label' => 'Slightly Frowning Face'],
            ['value' => '☹️', 'label' => 'Frowning Face'],
            ['value' => '😣', 'label' => 'Persevering Face'],
            ['value' => '😖', 'label' => 'Confounded Face'],
            ['value' => '😫', 'label' => 'Tired Face'],
            ['value' => '😩', 'label' => 'Weary Face'],
            ['value' => '🥺', 'label' => 'Pleading Face'],
            ['value' => '😢', 'label' => 'Crying Face'],
            ['value' => '😭', 'label' => 'Loudly Crying Face'],
            ['value' => '😮‍💨', 'label' => 'Face Exhaling'],
            ['value' => '😤', 'label' => 'Face with Steam from Nose'],
            ['value' => '😠', 'label' => 'Angry Face'],
            ['value' => '😡', 'label' => 'Pouting Face'],
            ['value' => '🤬', 'label' => 'Face with Symbols on Mouth'],
            ['value' => '🤯', 'label' => 'Exploding Head'],
            ['value' => '😳', 'label' => 'Flushed Face'],
            ['value' => '🥵', 'label' => 'Hot Face'],
            ['value' => '🥶', 'label' => 'Cold Face'],
            ['value' => '😱', 'label' => 'Screaming in Fear'],
            ['value' => '😨', 'label' => 'Fearful Face'],
            ['value' => '😰', 'label' => 'Anxious Face with Sweat'],
            ['value' => '😥', 'label' => 'Sad but Relieved Face'],
            ['value' => '😓', 'label' => 'Downcast Face with Sweat'],
            ['value' => '🫣', 'label' => 'Face with Peeking Eye'],
            ['value' => '🤗', 'label' => 'Hugging Face'],
            ['value' => '🫡', 'label' => 'Saluting Face'],
            ['value' => '🤔', 'label' => 'Thinking Face'],
            ['value' => '🫢', 'label' => 'Face with Open Eyes and Hand Over Mouth'],
            ['value' => '🤭', 'label' => 'Face with Hand Over Mouth'],
            ['value' => '🤫', 'label' => 'Shushing Face'],
            ['value' => '🤥', 'label' => 'Lying Face'],
            ['value' => '😶', 'label' => 'Face Without Mouth'],
            ['value' => '😶‍🌫️', 'label' => 'Face in Clouds'],
            ['value' => '😐', 'label' => 'Neutral Face'],
            ['value' => '😑', 'label' => 'Expressionless Face'],
            ['value' => '😬', 'label' => 'Grimacing Face'],
            ['value' => '🫨', 'label' => 'Face with Open Mouth and Cold Sweat'],
            ['value' => '🫠', 'label' => 'Face with Open Mouth and Hand Over Eyes'],
            ['value' => '🙄', 'label' => 'Face with Rolling Eyes'],
            ['value' => '😯', 'label' => 'Hushed Face'],
            ['value' => '😦', 'label' => 'Astonished Face'],
            ['value' => '😧', 'label' => 'Anguished Face'],
            ['value' => '😮', 'label' => 'Face with Open Mouth'],
            ['value' => '😲', 'label' => 'Astonished Face'],
            ['value' => '🥱', 'label' => 'Yawning Face'],
            ['value' => '😴', 'label' => 'Sleeping Face'],
            ['value' => '🤤', 'label' => 'Drooling Face'],
            ['value' => '😪', 'label' => 'Sleepy Face'],
            ['value' => '😵', 'label' => 'Dizzy Face'],
            ['value' => '😵‍💫', 'label' => 'Face with Spiral Eyes'],
            ['value' => '🫥', 'label' => 'Face with Open Mouth and Hand Over Mouth'],
            ['value' => '🤐', 'label' => 'Zipper-Mouth Face'],
            ['value' => '🥴', 'label' => 'Wozy Face'],
            ['value' => '🤢', 'label' => 'Nauseated Face'],
            ['value' => '🤮', 'label' => 'Face Vomiting'],
            ['value' => '🤧', 'label' => 'Sneezing Face'],
            ['value' => '😷', 'label' => 'Face with Medical Mask'],
            ['value' => '🤒', 'label' => 'Face with Thermometer'],
            ['value' => '🤕', 'label' => 'Face with Head-Bandage'],
            ['value' => '🤑', 'label' => 'Money-Mouth Face'],
            ['value' => '🤠', 'label' => 'Cowboy Hat Face'],
            ['value' => '😈', 'label' => 'Smiling Face with Horns'],
            ['value' => '👿', 'label' => 'Angry Face with Horns'],
            ['value' => '👹', 'label' => 'Ogre'],
            ['value' => '👺', 'label' => 'Goblin'],
            ['value' => '🤡', 'label' => 'Clown Face'],
            ['value' => '💩', 'label' => 'Pile of Poo'],
            ['value' => '👻', 'label' => 'Ghost'],
            ['value' => '💀', 'label' => 'Skull'],
            ['value' => '☠️', 'label' => 'Skull and Crossbones'],
            ['value' => '👽', 'label' => 'Name Badge'],
            ['value' => '👾', 'label' => 'Alien Monster'],
            ['value' => '🤖', 'label' => 'Robot Face'],
            ['value' => '🎃', 'label' => 'Jack-O-Lantern'],
            ['value' => '😺', 'label' => 'Smiling Cat Face'],
            ['value' => '😸', 'label' => 'Grinning Cat Face with Smiling Eyes'],
            ['value' => '😹', 'label' => 'Cat Face with Tears of Joy'],
            ['value' => '😻', 'label' => 'Heart Eyes Cat'],
            ['value' => '😼', 'label' => 'Cat Face with Wry Smile'],
            ['value' => '😽', 'label' => 'Kissing Cat Face'],
            ['value' => '🙀', 'label' => 'Weary Cat Face'],
            ['value' => '😿', 'label' => 'Crying Cat Face'],
            ['value' => '😾', 'label' => 'Pouting Cat Face'],
            ['value' => '👋', 'label' => 'Waving Hand'],
            ['value' => '🤚', 'label' => 'Raised Back of Hand'],
            ['value' => '🖐', 'label' => 'Hand with Fingers Splayed'],
            ['value' => '✋', 'label' => 'Raised Hand'],
            ['value' => '🖖', 'label' => 'Vulcan Salute'],
            ['value' => '👌', 'label' => 'OK Hand'],
            ['value' => '🤌', 'label' => 'Pinched Fingers'],
            ['value' => '🤏', 'label' => 'Pinching Hand'],
            ['value' => '✌️', 'label' => 'Victory Hand'],
            ['value' => '🤞', 'label' => 'Crossed Fingers'],
            ['value' => '🫰', 'label' => 'Hand with Index Finger and Thumb Crossed'],
            ['value' => '🤟', 'label' => 'Love-You Gesture'],
            ['value' => '🤘', 'label' => 'Sign of the Horns'],
            ['value' => '🤙', 'label' => 'Call Me Hand'],
            ['value' => '🫵', 'label' => 'Index Pointing at the Viewer'],
            ['value' => '🫱', 'label' => 'Palm Up Hand'],
            ['value' => '💦', 'label' => 'Wet Water'],
            ['value' => '🫲', 'label' => 'Palm Down Hand'],
            ['value' => '🫸', 'label' => 'Hand with Index Finger Pointing Up'],
            ['value' => '🫷', 'label' => 'Hand with Index Finger Pointing Down'],
            ['value' => '🫳', 'label' => 'Hand with Index Finger Pointing Left'],
            ['value' => '🫴', 'label' => 'Hand with Index Finger Pointing Right'],
            ['value' => '👈', 'label' => 'Backhand Index Pointing Left'],
            ['value' => '👉', 'label' => 'Backhand Index Pointing Right'],
            ['value' => '👆', 'label' => 'Backhand Index Pointing Up'],
            ['value' => '🖕', 'label' => 'Middle Finger'],
            ['value' => '👇', 'label' => 'Backhand Index Pointing Down'],
            ['value' => '☝️', 'label' => 'Index Pointing Up'],
            ['value' => '👍', 'label' => 'Thumbs Up'],
            ['value' => '👎', 'label' => 'Thumbs Down'],
            ['value' => '✊', 'label' => 'Raised Fist'],
            ['value' => '👊', 'label' => 'Fist Bump'],
            ['value' => '🤛', 'label' => 'Left-Facing Fist'],
            ['value' => '🤜', 'label' => 'Right-Facing Fist'],
            ['value' => '👏', 'label' => 'Clapping Hands'],
            ['value' => '🫶', 'label' => 'Heart Hands'],
            ['value' => '🙌', 'label' => 'Raising Hands'],
            ['value' => '👐', 'label' => 'Open Hands'],
            ['value' => '🤲', 'label' => 'Palms Up Together'],
            ['value' => '🤝', 'label' => 'Handshake'],
            ['value' => '🙏', 'label' => 'Folded Hands'],
            ['value' => '✍️', 'label' => 'Writing Hand'],
            ['value' => '💅', 'label' => 'Nail Polish'],
            ['value' => '🤳', 'label' => 'Selfie'],
            ['value' => '💪', 'label' => 'Flexed Biceps'],
            ['value' => '🦾', 'label' => 'Mechanical Arm'],
            ['value' => '🦵', 'label' => 'Leg'],
            ['value' => '🦿', 'label' => 'Prosthetic Leg'],
            ['value' => '🦶', 'label' => 'Foot'],
            ['value' => '👣', 'label' => 'Footprints'],
            ['value' => '👂', 'label' => 'Cup with Straw'],
            ['value' => '🦻', 'label' => 'Hearing Aid'],
            ['value' => '👃', 'label' => 'Nose'],
            ['value' => '🫀', 'label' => 'Anatomical Heart'],
            ['value' => '🫁', 'label' => 'Lungs'],
            ['value' => '🧠', 'label' => 'Brain'],
            ['value' => '🦷', 'label' => 'Tooth'],
            ['value' => '🦴', 'label' => 'Bone'],
            ['value' => '👀', 'label' => 'Eyes'],
            ['value' => '👁', 'label' => 'Eye'],
            ['value' => '👅', 'label' => 'Tongue'],
            ['value' => '👄', 'label' => 'Mouth'],
            ['value' => '🫦', 'label' => 'Biting Lip'],
            ['value' => '💋', 'label' => 'Kiss Mark'],
            ['value' => '🩸', 'label' => 'Blood Drop'],
            ['value' => '👶', 'label' => 'Baby'],
            ['value' => '👧', 'label' => 'Girl'],
            ['value' => '🧒', 'label' => 'Child'],
            ['value' => '👦', 'label' => 'Boy'],
            ['value' => '👩', 'label' => 'Woman'],
            ['value' => '🧑', 'label' => 'Person'],
            ['value' => '👨', 'label' => 'Man'],
            ['value' => '👩‍🦱', 'label' => 'Woman: Curly Hair'],
            ['value' => '🧑‍🦱', 'label' => 'Person: Curly Hair'],
            ['value' => '👨‍🦱', 'label' => 'Man: Curly Hair'],
            ['value' => '👩‍🦰', 'label' => 'Woman: Red Hair'],
            ['value' => '🧑‍🦰', 'label' => 'Person: Red Hair'],
            ['value' => '👨‍🦰', 'label' => 'Man: Red Hair'],
            ['value' => '👱‍♀️', 'label' => 'Woman: Blond Hair'],
            ['value' => '👱', 'label' => 'Person: Blond Hair'],
            ['value' => '👱‍♂️', 'label' => 'Man: Blond Hair'],
            ['value' => '👩‍🦳', 'label' => 'Woman: White Hair'],
            ['value' => '🧑‍🦳', 'label' => 'Person: White Hair'],
            ['value' => '👨‍🦳', 'label' => 'Man: White Hair'],
            ['value' => '👩‍🦲', 'label' => 'Woman: Bald'],
            ['value' => '🧑‍🦲', 'label' => 'Person: Bald'],
            ['value' => '👨‍🦲', 'label' => 'Man: Bald'],
            ['value' => '🧔‍♀️', 'label' => 'Woman with Beard'],
            ['value' => '🧔', 'label' => 'Person with Beard'],
            ['value' => '🧔‍♂️', 'label' => 'Man with Beard'],
            ['value' => '👵', 'label' => 'Older Woman'],
            ['value' => '🧓', 'label' => 'Older Person'],
            ['value' => '👴', 'label' => 'Old Man'],
            ['value' => '👲', 'label' => 'Person with Skullcap'],
            ['value' => '👳‍♀️', 'label' => 'Woman with Turban'],
            ['value' => '👳', 'label' => 'Person with Turban'],
            ['value' => '👳‍♂️', 'label' => 'Man with Turban'],
            ['value' => '🧕', 'label' => 'Woman with Headscarf'],
            ['value' => '👮‍♀️', 'label' => 'Woman Police Officer'],
            ['value' => '👮', 'label' => 'Police Officer'],
            ['value' => '👮‍♂️', 'label' => 'Man Police Officer'],
            ['value' => '👷‍♀️', 'label' => 'Woman Construction Worker'],
            ['value' => '👷', 'label' => 'Construction Worker'],
            ['value' => '👷‍♂️', 'label' => 'Man Construction Worker'],
            ['value' => '💂‍♀️', 'label' => 'Woman Guard'],
            ['value' => '💂', 'label' => 'Guard'],
            ['value' => '💂‍♂️', 'label' => 'Man Guard'],
            ['value' => '🕵️‍♀️', 'label' => 'Woman Detective'],
            ['value' => '🕵️', 'label' => 'Detective'],
            ['value' => '🕵️‍♂️', 'label' => 'Man Detective'],
            ['value' => '👩‍⚕️', 'label' => 'Woman Health Worker'],
            ['value' => '🧑‍⚕️', 'label' => 'Person Health Worker'],
            ['value' => '👨‍⚕️', 'label' => 'Man Health Worker'],
            ['value' => '👩‍🌾', 'label' => 'Woman Farmer'],
            ['value' => '🧑‍🌾', 'label' => 'Person Farmer'],
            ['value' => '👨‍🌾', 'label' => 'Man Farmer'],
            ['value' => '👩‍🍳', 'label' => 'Woman Cook'],
            ['value' => '🧑‍🍳', 'label' => 'Person Cook'],
            ['value' => '👨‍🍳', 'label' => 'Man Cook'],
            ['value' => '👩‍🎓', 'label' => 'Woman Student'],
            ['value' => '🧑‍🎓', 'label' => 'Person Student'],
            ['value' => '👨‍🎓', 'label' => 'Man Student'],
            ['value' => '👩‍🎤', 'label' => 'Woman Singer'],
            ['value' => '🧑‍🎤', 'label' => 'Person Singer'],
            ['value' => '👨‍🎤', 'label' => 'Man Singer'],
            ['value' => '👩‍🏫', 'label' => 'Woman Teacher'],
            ['value' => '🧑‍🏫', 'label' => 'Person Teacher'],
            ['value' => '👨‍🏫', 'label' => 'Man Teacher'],
            ['value' => '👩‍🏭', 'label' => 'Woman Factory Worker'],
            ['value' => '🧑‍🏭', 'label' => 'Person Factory Worker'],
            ['value' => '👨‍🏭', 'label' => 'Man Factory Worker'],
            ['value' => '👩‍💻', 'label' => 'Woman Technologist'],
            ['value' => '🧑‍💻', 'label' => 'Person Technologist'],
            ['value' => '👨‍💻', 'label' => 'Man Technologist'],
            ['value' => '👩‍💼', 'label' => 'Woman Office Worker'],
            ['value' => '🧑‍💼', 'label' => 'Person Office Worker'],
            ['value' => '👨‍💼', 'label' => 'Man Office Worker'],
            ['value' => '👩‍🔧', 'label' => 'Woman Mechanic'],
            ['value' => '🧑‍🔧', 'label' => 'Person Mechanic'],
            ['value' => '👨‍🔧', 'label' => 'Man Mechanic'],
            ['value' => '👩‍🔬', 'label' => 'Woman Scientist'],
            ['value' => '🧑‍🔬', 'label' => 'Person Scientist'],
            ['value' => '👨‍🔬', 'label' => 'Man Scientist'],
            ['value' => '👩‍🎨', 'label' => 'Woman Artist'],
            ['value' => '🧑‍🎨', 'label' => 'Person Artist'],
            ['value' => '👨‍🎨', 'label' => 'Man Artist'],
            ['value' => '👩‍🚒', 'label' => 'Woman Firefighter'],
            ['value' => '🧑‍🚒', 'label' => 'Person Firefighter'],
            ['value' => '👨‍🚒', 'label' => 'Man Firefighter'],
            ['value' => '👩‍✈️', 'label' => 'Woman Pilot'],
            ['value' => '🧑‍✈️', 'label' => 'Person Pilot'],
            ['value' => '👨‍✈️', 'label' => 'Man Pilot'],
            ['value' => '👩‍🚀', 'label' => 'Woman Astronaut'],
            ['value' => '🧑‍🚀', 'label' => 'Person Astronaut'],
            ['value' => '👨‍🚀', 'label' => 'Man Astronaut'],
            ['value' => '👩‍⚖️', 'label' => 'Woman Judge'],
            ['value' => '🧑‍⚖️', 'label' => 'Person Judge'],
            ['value' => '👨‍⚖️', 'label' => 'Man Judge'],
            ['value' => '👰‍♀️', 'label' => 'Woman with Veil'],
            ['value' => '👰', 'label' => 'Person with Veil'],
            ['value' => '👰‍♂️', 'label' => 'Man with Veil'],
            ['value' => '🤵‍♀️', 'label' => 'Woman in Tuxedo'],
            ['value' => '🤵', 'label' => 'Person in Tuxedo'],
            ['value' => '🤵‍♂️', 'label' => 'Man in Tuxedo'],
            ['value' => '👸', 'label' => 'Princess'],
            ['value' => '🤴', 'label' => 'Prince'],
            ['value' => '👵', 'label' => 'Older Woman'],
            ['value' => '👴', 'label' => 'Old Man'],
            ['value' => '🧓', 'label' => 'Older Person'],
            ['value' => '👳', 'label' => 'Person with Turban'],
            ['value' => '🧕', 'label' => 'Woman with Headscarf'],
            ['value' => '👩‍🌾', 'label' => 'Woman Farmer'],
            ['value' => '👩‍🏫', 'label' => 'Woman Teacher'],
            ['value' => '👩‍⚕️', 'label' => 'Woman Health Worker'],
            ['value' => '👩‍🔬', 'label' => 'Woman Scientist'],
            ['value' => '👩‍🚒', 'label' => 'Woman Firefighter'],
            ['value' => '👩‍✈️', 'label' => 'Woman Pilot'],
            ['value' => '👩‍🚀', 'label' => 'Woman Astronaut'],
            ['value' => '👩‍⚖️', 'label' => 'Woman Judge'],
            ['value' => '👮', 'label' => 'Police Officer'],
            ['value' => '👷', 'label' => 'Construction Worker'],
            ['value' => '💂', 'label' => 'Guard'],
            ['value' => '🕵️', 'label' => 'Detective'],
            ['value' => '👨‍⚕️', 'label' => 'Man Health Worker'],
            ['value' => '👨‍🌾', 'label' => 'Man Farmer'],
            ['value' => '👨‍🍳', 'label' => 'Man Cook'],
            ['value' => '👨‍🎓', 'label' => 'Man Student'],
            ['value' => '👨‍🎤', 'label' => 'Man Singer'],
            ['value' => '👨‍🏫', 'label' => 'Man Teacher'],
            ['value' => '👨‍🏭', 'label' => 'Man Factory Worker'],
            ['value' => '👨‍💻', 'label' => 'Man Technologist'],
            ['value' => '👨‍💼', 'label' => 'Man Office Worker'],
            ['value' => '👨‍🔧', 'label' => 'Man Mechanic'],
            ['value' => '👨‍🔬', 'label' => 'Man Scientist'],
            ['value' => '👨‍🎨', 'label' => 'Man Artist'],
            ['value' => '👨‍🚒', 'label' => 'Man Firefighter'],
            ['value' => '👨‍✈️', 'label' => 'Man Pilot'],
            ['value' => '👨‍🚀', 'label' => 'Man Astronaut'],
            ['value' => '👨‍⚖️', 'label' => 'Man Judge'],
            ['value' => '👗', 'label' => 'Dress'],
            ['value' => '👘', 'label' => 'Kimono'],
            ['value' => '🥻', 'label' => 'Sari'],
            ['value' => '🩴', 'label' => 'Thong Sandal'],
            ['value' => '🩱', 'label' => 'One-Piece Swimsuit'],
            ['value' => '🩲', 'label' => 'Briefs'],
            ['value' => '🩳', 'label' => 'Shorts'],
            ['value' => '👙', 'label' => 'Bikini'],
            ['value' => '👚', 'label' => 'Woman’s Clothes'],
            ['value' => '👛', 'label' => 'Purse'],
            ['value' => '👜', 'label' => 'Handbag'],
            ['value' => '👝', 'label' => 'Clutch Bag'],
            ['value' => '🎒', 'label' => 'Backpack'],
            ['value' => '👞', 'label' => 'Mans Shoe'],
            ['value' => '👟', 'label' => 'Running Shoe'],
            ['value' => '🥾', 'label' => 'Hiking Boot'],
            ['value' => '🥿', 'label' => 'Flat Shoe'],
            ['value' => '👠', 'label' => 'High-Heeled Shoe'],
            ['value' => '👡', 'label' => 'Woman’s Sandal'],
            ['value' => '🩰', 'label' => 'Ballet Shoes'],
            ['value' => '👢', 'label' => 'Light'],
            ['value' => '👑', 'label' => 'Crown'],
            ['value' => '👒', 'label' => 'Hat'],
            ['value' => '🎩', 'label' => 'Top Hat'],
            ['value' => '🎓', 'label' => 'Graduation Cap'],
            ['value' => '🧢', 'label' => 'Billed Cap'],
            ['value' => '⛑', 'label' => 'Helmet'],
            ['value' => '🪖', 'label' => 'Military Helmet'],
            ['value' => '💄', 'label' => 'Lipstick'],
            ['value' => '💍', 'label' => 'Ring'],
            ['value' => '💼', 'label' => 'Briefcase'],
            ['value' => '🐶', 'label' => 'Dog'],
            ['value' => '🐱', 'label' => 'Cat'],
            ['value' => '🐭', 'label' => 'Mouse'],
            ['value' => '🐹', 'label' => 'Hamster'],
            ['value' => '🐰', 'label' => 'Rabbit'],
            ['value' => '🦊', 'label' => 'Fish'],
            ['value' => '🐻', 'label' => 'Bear'],
            ['value' => '🐼', 'label' => 'Panda'],
            ['value' => '🐻‍❄️', 'label' => 'Polar Bear'],
            ['value' => '🐨', 'label' => 'Koala'],
            ['value' => '🐯', 'label' => 'Tiger'],
            ['value' => '🦁', 'label' => 'Lion'],
            ['value' => '🐮', 'label' => 'Cow'],
            ['value' => '🐷', 'label' => 'Pig'],
            ['value' => '🐽', 'label' => 'Pig Nose'],
            ['value' => '🐸', 'label' => 'Frog'],
            ['value' => '🐵', 'label' => 'Monkey'],
            ['value' => '🙈', 'label' => 'See-No-Evil Monkey'],
            ['value' => '🙉', 'label' => 'Hear-No-Evil Monkey'],
            ['value' => '🙊', 'label' => 'Speak-No-Evil Monkey'],
            ['value' => '🐒', 'label' => 'Monkey Face'],
            ['value' => '🐔', 'label' => 'Chicken'],
            ['value' => '🐧', 'label' => 'Penguin'],
            ['value' => '🐦', 'label' => 'Bird'],
            ['value' => '🐦‍⬛', 'label' => 'Black Bird'],
            ['value' => '🐤', 'label' => 'Baby Chick'],
            ['value' => '🐣', 'label' => 'Hatching Chick'],
            ['value' => '🐥', 'label' => 'Front-Facing Baby Chick'],
            ['value' => '🦆', 'label' => 'Duck'],
            ['value' => '🦅', 'label' => 'Eagle'],
            ['value' => '🦉', 'label' => 'Owl'],
            ['value' => '🦇', 'label' => 'Bat'],
            ['value' => '🐺', 'label' => 'Wolf'],
            ['value' => '🐗', 'label' => 'Boar'],
            ['value' => '🐴', 'label' => 'Horse'],
            ['value' => '🦄', 'label' => 'Unicorn'],
            ['value' => '🐝', 'label' => 'Bee'],
            ['value' => '🪱', 'label' => 'Worm'],
            ['value' => '🐛', 'label' => 'Bug'],
            ['value' => '🦋', 'label' => 'Butterfly'],
            ['value' => '🐌', 'label' => 'Snail'],
            ['value' => '🐞', 'label' => 'Lady Beetle'],
            ['value' => '🐜', 'label' => 'Ant'],
            ['value' => '🪰', 'label' => 'Fly'],
            ['value' => '🪲', 'label' => 'Beetle'],
            ['value' => '🪳', 'label' => 'Cockroach'],
            ['value' => '🦟', 'label' => 'Mosquito'],
            ['value' => '🦗', 'label' => 'Cricket'],
            ['value' => '🕷', 'label' => 'Spider'],
            ['value' => '🕸', 'label' => 'Spider Web'],
            ['value' => '🦂', 'label' => 'Scorpion'],
            ['value' => '🐢', 'label' => 'Turtle'],
            ['value' => '🐍', 'label' => 'Snake'],
            ['value' => '🦎', 'label' => 'Lizard'],
            ['value' => '🦖', 'label' => 'Sauropod'],
            ['value' => '🦕', 'label' => 'Sauropod'],
            ['value' => '🐙', 'label' => 'Octopus'],
            ['value' => '🦑', 'label' => 'Squid'],
            ['value' => '🦐', 'label' => 'Shrimp'],
            ['value' => '🦞', 'label' => 'Lobster'],
            ['value' => '🦀', 'label' => 'Crab'],
            ['value' => '🪼', 'label' => 'Jellyfish'],
            ['value' => '🪸', 'label' => 'Coral'],
            ['value' => '🐡', 'label' => 'Blowfish'],
            ['value' => '🐠', 'label' => 'Tropical Fish'],
            ['value' => '🐟', 'label' => 'Fish'],
            ['value' => '🐬', 'label' => 'Dolphin'],
            ['value' => '🐳', 'label' => 'Whale'],
            ['value' => '🐋', 'label' => 'Whale'],
            ['value' => '🦈', 'label' => 'Shark'],
            ['value' => '🐊', 'label' => 'Crocodile'],
            ['value' => '🐅', 'label' => 'Tiger'],
            ['value' => '🐆', 'label' => 'Leopard'],
            ['value' => '🦓', 'label' => 'Zebra'],
            ['value' => '🫏', 'label' => 'Giraffe'],
            ['value' => '🦍', 'label' => 'Gorilla'],
            ['value' => '🦧', 'label' => 'Orangutan'],
            ['value' => '🦣', 'label' => 'Dromedary Camel'],
            ['value' => '🐘', 'label' => 'Elephant'],
            ['value' => '🦛', 'label' => 'Hippopotamus'],
            ['value' => '🦏', 'label' => 'Rhinoceros'],
            ['value' => '🐪', 'label' => 'Camel'],
            ['value' => '🐫', 'label' => 'Two-Hump Camel'],
            ['value' => '🦒', 'label' => 'Giraffe'],
            ['value' => '🦙', 'label' => 'Donkey'],
            ['value' => '🦧', 'label' => 'Orangutan'],
            ['value' => '🐴', 'label' => 'Horse'],
            ['value' => '🦓', 'label' => 'Zebra'],
            ['value' => '🦒', 'label' => 'Giraffe'],
            ['value' => '🦄', 'label' => 'Unicorn'],
            ['value' => '🐎', 'label' => 'Horse'],
            ['value' => '🦄', 'label' => 'Unicorn'],
            ['value' => '🦙', 'label' => 'Donkey'],
            ['value' => '🦝', 'label' => 'Llama'],
            ['value' => '🦣', 'label' => 'Dromedary Camel'],
            ['value' => '🦛', 'label' => 'Hippopotamus'],
            ['value' => '🦏', 'label' => 'Rhinoceros'],
            ['value' => '🦢', 'label' => 'Elephant'],
            ['value' => '🍅', 'label' => 'Tomato'],
            ['value' => '🍆', 'label' => 'Eggplant'],
            ['value' => '🥑', 'label' => 'Avocado'],
            ['value' => '🥦', 'label' => 'Broccoli'],
            ['value' => '🫛', 'label' => 'Peas'],
            ['value' => '🥬', 'label' => 'Leafy Green'],
            ['value' => '🥒', 'label' => 'Cucumber'],
            ['value' => '🌶', 'label' => 'Hot Pepper'],
            ['value' => '🫑', 'label' => 'Bell Pepper'],
            ['value' => '🌽', 'label' => 'Corn'],
            ['value' => '🥕', 'label' => 'Carrot'],
            ['value' => '🫒', 'label' => 'Olive'],
            ['value' => '🧄', 'label' => 'Garlic'],
            ['value' => '🧅', 'label' => 'Shallot'],
            ['value' => '🫚', 'label' => 'Date'],
            ['value' => '🥔', 'label' => 'Potato'],
            ['value' => '🍠', 'label' => 'Sweet Potato'],
            ['value' => '🫘', 'label' => 'Beans'],
            ['value' => '🥐', 'label' => 'Croissant'],
            ['value' => '🥯', 'label' => 'Bagel'],
            ['value' => '🍞', 'label' => 'Bread'],
            ['value' => '🥖', 'label' => 'Baguette'],
            ['value' => '🥨', 'label' => 'Pretzel'],
            ['value' => '🧀', 'label' => 'Cheese'],
            ['value' => '🥚', 'label' => 'Egg'],
            ['value' => '🍳', 'label' => 'Cooking'],
            ['value' => '🧈', 'label' => 'Butter'],
            ['value' => '🥞', 'label' => 'Pancakes'],
            ['value' => '🧇', 'label' => 'Waffle'],
            ['value' => '🥓', 'label' => 'Bacon'],
            ['value' => '🥩', 'label' => 'Steak'],
            ['value' => '🍗', 'label' => 'Poultry Leg'],
            ['value' => '🍖', 'label' => 'Meat on Bone'],
            ['value' => '🦴', 'label' => 'Bone'],
            ['value' => '🌭', 'label' => 'Hot Dog'],
            ['value' => '🍔', 'label' => 'Hamburger'],
            ['value' => '🍟', 'label' => 'French Fries'],
            ['value' => '🍕', 'label' => 'Pizza'],
            ['value' => '🫓', 'label' => 'Flatbread'],
            ['value' => '🥪', 'label' => 'Sandwich'],
            ['value' => '🥙', 'label' => 'Stuffed Flatbread'],
            ['value' => '🧆', 'label' => 'Falafel'],
            ['value' => '🌮', 'label' => 'Taco'],
            ['value' => '🌯', 'label' => 'Burrito'],
            ['value' => '🫔', 'label' => 'Tamale'],
            ['value' => '🥗', 'label' => 'Salad'],
            ['value' => '🥘', 'label' => 'Shallow Pan of Food'],
            ['value' => '🫕', 'label' => 'Fondue'],
            ['value' => '🥫', 'label' => 'Canned Food'],
            ['value' => '🍝', 'label' => 'Spaghetti'],
            ['value' => '🍜', 'label' => 'Steaming Bowl'],
            ['value' => '🍲', 'label' => 'Pot of Food'],
            ['value' => '🍛', 'label' => 'Curry Rice'],
            ['value' => '🍣', 'label' => 'Sushi'],
            ['value' => '🍱', 'label' => 'Bento Box'],
            ['value' => '🥟', 'label' => 'Dumpling'],
            ['value' => '🦪', 'label' => 'Oyster'],
            ['value' => '🍤', 'label' => 'Fried Shrimp'],
            ['value' => '🍙', 'label' => 'Rice Ball'],
            ['value' => '🍚', 'label' => 'Cooked Rice'],
            ['value' => '🍘', 'label' => 'Rice Cracker'],
            ['value' => '🍥', 'label' => 'Fish Cake'],
            ['value' => '🥠', 'label' => 'Fortune Cookie'],
            ['value' => '🥮', 'label' => 'Moon Cake'],
            ['value' => '🍢', 'label' => 'Kebab'],
            ['value' => '🍡', 'label' => 'Dango'],
            ['value' => '🍧', 'label' => 'Shaved Ice'],
            ['value' => '🍨', 'label' => 'Ice Cream'],
            ['value' => '🍦', 'label' => 'Soft Ice Cream'],
            ['value' => '🥧', 'label' => 'Pie'],
            ['value' => '🧁', 'label' => 'Cupcake'],
            ['value' => '🍰', 'label' => 'Shortcake'],
            ['value' => '🎂', 'label' => 'Birthday Cake'],
            ['value' => '🍮', 'label' => 'Flan'],
            ['value' => '🍭', 'label' => 'Lollipop'],
            ['value' => '🍬', 'label' => 'Candy'],
            ['value' => '🍫', 'label' => 'Chocolate Bar'],
            ['value' => '🍿', 'label' => 'Popcorn'],
            ['value' => '🍩', 'label' => 'Doughnut'],
            ['value' => '🍪', 'label' => 'Cookie'],
            ['value' => '🌰', 'label' => 'Chestnut'],
            ['value' => '🥜', 'label' => 'Peanuts'],
            ['value' => '🍯', 'label' => 'Honey Pot'],
            ['value' => '🥛', 'label' => 'Glass of Milk'],
            ['value' => '🍼', 'label' => 'Baby Bottle'],
            ['value' => '🫖', 'label' => 'Teapot'],
            ['value' => '☕️', 'label' => 'Coffee'],
            ['value' => '🍵', 'label' => 'Teacup Without Handle'],
            ['value' => '🧃', 'label' => 'Juice'],
            ['value' => '🥤', 'label' => 'Cup with Straw'],
            ['value' => '🧋', 'label' => 'Bubble Tea'],
            ['value' => '🫙', 'label' => 'Jar'],
            ['value' => '🍶', 'label' => 'Sake Bottle'],
            ['value' => '🍺', 'label' => 'Beer Mug'],
            ['value' => '🍻', 'label' => 'Clinking Beer Mugs'],
            ['value' => '🥂', 'label' => 'Clinking Glasses'],
            ['value' => '🍷', 'label' => 'Wine Glass'],
            ['value' => '🫗', 'label' => 'Cocktail Glass'],
            ['value' => '🥃', 'label' => 'Tumbler Glass'],
            ['value' => '🍸', 'label' => 'Cocktail Glass'],
            ['value' => '🍹', 'label' => 'Tropical Drink'],
            ['value' => '🧉', 'label' => 'Mate'],
            ['value' => '🍾', 'label' => 'Bottle with Popping Cork'],
            ['value' => '🧊', 'label' => 'Ice Cube'],
            ['value' => '🥄', 'label' => 'Spoon'],
            ['value' => '🍴', 'label' => 'Fork and Knife'],
            ['value' => '🍽', 'label' => 'Fork and Knife with Plate'],
            ['value' => '🥣', 'label' => 'Bowl with Spoon'],
            ['value' => '🥡', 'label' => 'Takeout Box'],
            ['value' => '🥢', 'label' => 'Chopsticks'],
            ['value' => '🧂', 'label' => 'Salt'],
            ['value' => '⚽️', 'label' => 'Soccer Ball'],
            ['value' => '🏀', 'label' => 'Basketball'],
            ['value' => '🏈', 'label' => 'American Football'],
            ['value' => '⚾️', 'label' => 'Baseball'],
            ['value' => '🥎', 'label' => 'Softball'],
            ['value' => '🎾', 'label' => 'Tennis'],
            ['value' => '🏐', 'label' => 'Volleyball'],
            ['value' => '🏉', 'label' => 'Rugby Football'],
            ['value' => '🥏', 'label' => 'Flying Disc'],
            ['value' => '🎱', 'label' => 'Pool 8 Ball'],
            ['value' => '🪀', 'label' => 'Yo-Yo'],
            ['value' => '🏓', 'label' => 'Table Tennis Paddle and Ball'],
            ['value' => '🏸', 'label' => 'Badminton'],
            ['value' => '🏒', 'label' => 'Ice Hockey Stick and Puck'],
            ['value' => '🏑', 'label' => 'Field Hockey Stick and Ball'],
            ['value' => '🥍', 'label' => 'Lacrosse Stick and Ball'],
            ['value' => '🏏', 'label' => 'Cricket Bat and Ball'],
            ['value' => '🪃', 'label' => 'Boomerang'],
            ['value' => '🥅', 'label' => 'Goal Net'],
            ['value' => '⛳️', 'label' => 'Flag in Hole'],
            ['value' => '🪁', 'label' => 'Kite'],
            ['value' => '🏹', 'label' => 'Bow and Arrow'],
            ['value' => '🎣', 'label' => 'Fishing Pole'],
            ['value' => '🤿', 'label' => 'Diving Mask'],
            ['value' => '🥊', 'label' => 'Boxing Glove'],
            ['value' => '🥋', 'label' => 'Martial Arts Uniform'],
            ['value' => '🎽', 'label' => 'Running Shirt'],
            ['value' => '🛹', 'label' => 'Skateboard'],
            ['value' => '🛼', 'label' => 'Roller Skate'],
            ['value' => '🛷', 'label' => 'Sled'],
            ['value' => '⛸', 'label' => 'Ice Skate'],
            ['value' => '🥌', 'label' => 'Curling Stone'],
            ['value' => '🎿', 'label' => 'Skis'],
            ['value' => '⛷', 'label' => 'Skier'],
            ['value' => '🏂', 'label' => 'Snowboarder'],
            ['value' => '🪂', 'label' => 'Parachute'],
            ['value' => '🏋️‍♀️', 'label' => 'Woman Lifting Weights'],
            ['value' => '🏋️', 'label' => 'Weight Lifter'],
            ['value' => '🏋️‍♂️', 'label' => 'Man Lifting Weights'],
            ['value' => '🤼‍♀️', 'label' => 'Woman Wrestling'],
            ['value' => '🤼', 'label' => 'Wrestlers'],
            ['value' => '🤼‍♂️', 'label' => 'Man Wrestling'],
            ['value' => '🤸‍♀️', 'label' => 'Woman Cartwheeling'],
            ['value' => '🤸', 'label' => 'Person Cartwheeling'],
            ['value' => '🤸‍♂️', 'label' => 'Man Cartwheeling'],
            ['value' => '⛹️‍♀️', 'label' => 'Woman Bouncing Ball'],
            ['value' => '⛹️', 'label' => 'Person Bouncing Ball'],
            ['value' => '⛹️‍♂️', 'label' => 'Man Bouncing Ball'],
            ['value' => '🤺', 'label' => 'Fencer'],
            ['value' => '🤾‍♀️', 'label' => 'Woman Playing Handball'],
            ['value' => '🤾', 'label' => 'Person Playing Handball'],
            ['value' => '🤾‍♂️', 'label' => 'Man Playing Handball'],
            ['value' => '🏌️‍♀️', 'label' => 'Woman Golfing'],
            ['value' => '🏌️', 'label' => 'Golfer'],
            ['value' => '🏌️‍♂️', 'label' => 'Man Golfing'],
            ['value' => '🏇', 'label' => 'Horse Racing'],
            ['value' => '🧘‍♀️', 'label' => 'Woman in Lotus Position'],
            ['value' => '🧘', 'label' => 'Person in Lotus Position'],
            ['value' => '🧘‍♂️', 'label' => 'Man in Lotus Position'],
            ['value' => '🏄‍♀️', 'label' => 'Woman Surfing'],
            ['value' => '🏄', 'label' => 'Person Surfing'],
            ['value' => '🏄‍♂️', 'label' => 'Man Surfing'],
            ['value' => '🏊‍♀️', 'label' => 'Woman Swimming'],
            ['value' => '🏊', 'label' => 'Person Swimming'],
            ['value' => '🏊‍♂️', 'label' => 'Man Swimming'],
            ['value' => '🤽‍♀️', 'label' => 'Woman Playing Water Polo'],
            ['value' => '🤽', 'label' => 'Person Playing Water Polo'],
            ['value' => '🤽‍♂️', 'label' => 'Man Playing Water Polo'],
            ['value' => '🚣‍♀️', 'label' => 'Woman Rowing Boat'],
            ['value' => '🚣', 'label' => 'Person Rowing Boat'],
            ['value' => '🚣‍♂️', 'label' => 'Man Rowing Boat'],
            ['value' => '🧗‍♀️', 'label' => 'Woman Climbing'],
            ['value' => '🧗', 'label' => 'Person Climbing'],
            ['value' => '🧗‍♂️', 'label' => 'Man Climbing'],
            ['value' => '🚵‍♀️', 'label' => 'Woman Mountain Biking'],
            ['value' => '🚵', 'label' => 'Person Mountain Biking'],
            ['value' => '🚵‍♂️', 'label' => 'Man Mountain Biking'],
            ['value' => '🚴‍♀️', 'label' => 'Woman Biking'],
            ['value' => '🚴', 'label' => 'Person Biking'],
            ['value' => '🚴‍♂️', 'label' => 'Man Biking'],
            ['value' => '🏆', 'label' => 'Trophy'],
            ['value' => '🥇', 'label' => '1st Place Medal'],
            ['value' => '🥈', 'label' => '2nd Place Medal'],
            ['value' => '🥉', 'label' => '3rd Place Medal'],
            ['value' => '🏅', 'label' => 'Sports Medal'],
            ['value' => '🎖', 'label' => 'Military Medal'],
            ['value' => '🏵', 'label' => 'Rosette'],
            ['value' => '🎗', 'label' => 'Reminder Ribbon'],
            ['value' => '🎫', 'label' => 'Ticket'],
            ['value' => '🎟', 'label' => 'Admission Tickets'],
            ['value' => '🎪', 'label' => 'Circus Tent'],
            ['value' => '🤹', 'label' => 'Juggler'],
            ['value' => '🤹‍♂️', 'label' => 'Man Juggling'],
            ['value' => '🤹‍♀️', 'label' => 'Woman Juggling'],
            ['value' => '🎭', 'label' => 'Performing Arts'],
            ['value' => '🩰', 'label' => 'Ballet Shoes'],
            ['value' => '🎨', 'label' => 'Artist Palette'],
            ['value' => '🎬', 'label' => 'Clapper Board'],
            ['value' => '🎤', 'label' => 'Microphone'],
            ['value' => '🎧', 'label' => 'Headphone'],
            ['value' => '🎼', 'label' => 'Musical Score'],
            ['value' => '🎹', 'label' => 'Piano'],
            ['value' => '🥁', 'label' => 'Drum'],
            ['value' => '🪘', 'label' => 'Long Drum'],
            ['value' => '🪇', 'label' => 'Maraca'],
            ['value' => '🎷', 'label' => 'Saxophone'],
            ['value' => '🎺', 'label' => 'Trumpet'],
            ['value' => '🪗', 'label' => 'Accordion'],
            ['value' => '🎸', 'label' => 'Guitar'],
            ['value' => '🪕', 'label' => 'Banjo'],
            ['value' => '🎻', 'label' => 'Violin'],
            ['value' => '🪈', 'label' => 'Flute'],
            ['value' => '🎲', 'label' => 'Dice'],
            ['value' => '♟', 'label' => 'Chess Pawn'],
            ['value' => '🎯', 'label' => 'Direct Hit'],
            ['value' => '🎳', 'label' => 'Bowling'],
            ['value' => '🎮', 'label' => 'Video Game'],
            ['value' => '🎰', 'label' => 'Slot Machine'],
            ['value' => '🧩', 'label' => 'Puzzle Piece'],
            ['value' => '🚗', 'label' => 'Car'],
            ['value' => '🚕', 'label' => 'Taxi'],
            ['value' => '🚙', 'label' => 'SUV'],
            ['value' => '🚌', 'label' => 'Bus'],
            ['value' => '🚎', 'label' => 'Trolleybus'],
            ['value' => '🏎', 'label' => 'Racing Car'],
            ['value' => '🚓', 'label' => 'Police Car'],
            ['value' => '🚑', 'label' => 'Ambulance'],
            ['value' => '🚒', 'label' => 'Fire Truck'],
            ['value' => '🚐', 'label' => 'Minibus'],
            ['value' => '🛻', 'label' => 'Pickup Truck'],
            ['value' => '🚚', 'label' => 'Delivery Truck'],
            ['value' => '🚛', 'label' => 'Articulated Lorry'],
            ['value' => '🚜', 'label' => 'Tractor'],
            ['value' => '🦯', 'label' => 'White Cane'],
            ['value' => '🦽', 'label' => 'Manual Wheelchair'],
            ['value' => '🦼', 'label' => 'Motorized Wheelchair'],
            ['value' => '🛴', 'label' => 'Kick Scooter'],
            ['value' => '🚲', 'label' => 'Bicycle'],
            ['value' => '🛵', 'label' => 'Motor Scooter'],
            ['value' => '🏍', 'label' => 'Motorcycle'],
            ['value' => '🛺', 'label' => 'Auto Rickshaw'],
            ['value' => '🚨', 'label' => 'Emergency Vehicle Light'],
            ['value' => '🚔', 'label' => 'Police Car Light'],
            ['value' => '🚍', 'label' => 'Oncoming Bus'],
            ['value' => '🚘', 'label' => 'Oncoming Automobile'],
            ['value' => '🚖', 'label' => 'Oncoming Taxi'],
            ['value' => '🛞', 'label' => 'Wheel'],
            ['value' => '🚡', 'label' => 'Aerial Tramway'],
            ['value' => '🚠', 'label' => 'Mountain Cableway'],
            ['value' => '🚟', 'label' => 'Suspension Railway'],
            ['value' => '🚃', 'label' => 'Railway Car'],
            ['value' => '🚋', 'label' => 'Tram'],
            ['value' => '🚞', 'label' => 'Mountain Railway'],
            ['value' => '🚝', 'label' => 'Monorail'],
            ['value' => '🚄', 'label' => 'High-Speed Train'],
            ['value' => '🚅', 'label' => 'Bullet Train'],
            ['value' => '🚈', 'label' => 'Light Rail'],
            ['value' => '🚂', 'label' => 'Steam Locomotive'],
            ['value' => '🚆', 'label' => 'Train'],
            ['value' => '🚇', 'label' => 'Metro'],
            ['value' => '🚊', 'label' => 'Tram'],
            ['value' => '🚉', 'label' => 'Station'],
            ['value' => '✈️', 'label' => 'Airplane'],
            ['value' => '🛫', 'label' => 'Airplane Departure'],
            ['value' => '🛬', 'label' => 'Airplane Arrival'],
            ['value' => '🛩', 'label' => 'Small Airplane'],
            ['value' => '💺', 'label' => 'Seat'],
            ['value' => '🛰', 'label' => 'Satellite'],
            ['value' => '🚀', 'label' => 'Rocket'],
            ['value' => '🛸', 'label' => 'Flying Saucer'],
            ['value' => '🚁', 'label' => 'Helicopter'],
            ['value' => '🛶', 'label' => 'Canoe'],
            ['value' => '⛵️', 'label' => 'Sailboat'],
            ['value' => '🚤', 'label' => 'Speedboat'],
            ['value' => '🛥', 'label' => 'Motorboat'],
            ['value' => '🛳', 'label' => 'Boat'],
            ['value' => '⛴', 'label' => 'Ferry'],
            ['value' => '🚢', 'label' => 'Ship'],
            ['value' => '⚓️', 'label' => 'Anchor'],
            ['value' => '🛟', 'label' => 'Life Buoy'],
            ['value' => '🪝', 'label' => 'Hook'],
            ['value' => '⛽️', 'label' => 'Fuel Pump'],
            ['value' => '🚧', 'label' => 'Construction'],
            ['value' => '🚦', 'label' => 'Traffic Light'],
            ['value' => '🚥', 'label' => 'Horizontal Traffic Light'],
            ['value' => '🚏', 'label' => 'Bus Stop'],
            ['value' => '🗺', 'label' => 'World Map'],
            ['value' => '🗿', 'label' => 'Moai'],
            ['value' => '🗽', 'label' => 'Statue of Liberty'],
            ['value' => '🗼', 'label' => 'Eiffel Tower'],
            ['value' => '🏰', 'label' => 'Castle'],
            ['value' => '🏯', 'label' => 'Japanese Castle'],
            ['value' => '🏟', 'label' => 'Stadium'],
            ['value' => '🎡', 'label' => 'Ferris Wheel'],
            ['value' => '🎢', 'label' => 'Roller Coaster'],
            ['value' => '🛝', 'label' => 'Slide'],
            ['value' => '🎠', 'label' => 'Carousel Horse'],
            ['value' => '⛲️', 'label' => 'Fountain'],
            ['value' => '⛱', 'label' => 'Umbrella on Ground'],
            ['value' => '🏖', 'label' => 'Beach with Umbrella'],
            ['value' => '🏝', 'label' => 'Desert Island'],
            ['value' => '🏜', 'label' => 'Desert'],
            ['value' => '🌋', 'label' => 'Volcano'],
            ['value' => '⛰', 'label' => 'Mountain'],
            ['value' => '🏔', 'label' => 'Snow-Capped Mountain'],
            ['value' => '🗻', 'label' => 'Mount Fuji'],
            ['value' => '🏕', 'label' => 'Camping'],
            ['value' => '⛺️', 'label' => 'Tent'],
            ['value' => '🛖', 'label' => 'Hut'],
            ['value' => '🏠', 'label' => 'House'],
            ['value' => '🏡', 'label' => 'House with Garden'],
            ['value' => '🏘', 'label' => 'Houses'],
            ['value' => '🏚', 'label' => 'Derelict House'],
            ['value' => '🏗', 'label' => 'Building Construction'],
            ['value' => '🏭', 'label' => 'Factory'],
            ['value' => '🏢', 'label' => 'Office Building'],
            ['value' => '🏬', 'label' => 'Department Store'],
            ['value' => '🏣', 'label' => 'Post Office'],
            ['value' => '🏤', 'label' => 'Post Office Building'],
            ['value' => '🏥', 'label' => 'Hospital'],
            ['value' => '🏦', 'label' => 'Bank'],
            ['value' => '🏨', 'label' => 'Hotel'],
            ['value' => '🏪', 'label' => 'Convenience Store'],
            ['value' => '🏫', 'label' => 'School'],
            ['value' => '🏩', 'label' => 'Love Hotel'],
            ['value' => '💒', 'label' => 'Wedding'],
            ['value' => '🏛', 'label' => 'Classical Building'],
            ['value' => '⛪️', 'label' => 'Church'],
            ['value' => '🕌', 'label' => 'Mosque'],
            ['value' => '🕍', 'label' => 'Synagogue'],
            ['value' => '🛕', 'label' => 'Hindu Temple'],
            ['value' => '🕋', 'label' => 'Kaaba'],
            ['value' => '⛩', 'label' => 'Shinto Shrine'],
            ['value' => '🛤', 'label' => 'Railway Track'],
            ['value' => '🛣', 'label' => 'Motorway'],
            ['value' => '🗾', 'label' => 'Map of Japan'],
            ['value' => '🎑', 'label' => 'Rice Scene'],
            ['value' => '🏞', 'label' => 'National Park'],
            ['value' => '🌅', 'label' => 'Sunrise'],
            ['value' => '🌄', 'label' => 'Sunrise Over Mountains'],
            ['value' => '🌠', 'label' => 'Shooting Star'],
            ['value' => '🎇', 'label' => 'Fireworks'],
            ['value' => '🎆', 'label' => 'Fireworks'],
            ['value' => '🌇', 'label' => 'Sunset'],
            ['value' => '🌆', 'label' => 'Cityscape'],
            ['value' => '🏙', 'label' => 'Cityscape at Dusk'],
            ['value' => '🌃', 'label' => 'Night with Stars'],
            ['value' => '🌌', 'label' => 'Milky Way'],
            ['value' => '🌉', 'label' => 'Bridge at Night'],
            ['value' => '🌁', 'label' => 'Foggy'],
            ['value' => '⌚️', 'label' => 'Watch'],
            ['value' => '📱', 'label' => 'Mobile Phone'],
            ['value' => '📲', 'label' => 'Mobile Phone with Arrow'],
            ['value' => '💻', 'label' => 'Laptop'],
            ['value' => '⌨️', 'label' => 'Keyboard'],
            ['value' => '🖥', 'label' => 'Desktop Computer'],
            ['value' => '🖨', 'label' => 'Printer'],
            ['value' => '🖱', 'label' => 'Mouse'],
            ['value' => '🖲', 'label' => 'Trackball'],
            ['value' => '🕹', 'label' => 'Joystick'],
            ['value' => '🗜', 'label' => 'Clamp'],
            ['value' => '💽', 'label' => 'Minidisc'],
            ['value' => '💾', 'label' => 'Floppy Disk'],
            ['value' => '💿', 'label' => 'Optical Disc'],
            ['value' => '📀', 'label' => 'DVD'],
            ['value' => '📼', 'label' => 'Videocassette'],
            ['value' => '📷', 'label' => 'Camera'],
            ['value' => '📸', 'label' => 'Camera with Flash'],
            ['value' => '📹', 'label' => 'Video Camera'],
            ['value' => '🎥', 'label' => 'Movie Camera'],
            ['value' => '📽', 'label' => 'Film Projector'],
            ['value' => '🎞', 'label' => 'Film Frames'],
            ['value' => '📞', 'label' => 'Telephone Receiver'],
            ['value' => '☎️', 'label' => 'Telephone'],
            ['value' => '📟', 'label' => 'Pager'],
            ['value' => '📠', 'label' => 'Fax Machine'],
            ['value' => '📺', 'label' => 'Television'],
            ['value' => '📻', 'label' => 'Radio'],
            ['value' => '🎙', 'label' => 'Microphone'],
            ['value' => '🎚', 'label' => 'Level Slider'],
            ['value' => '🎛', 'label' => 'Control Knobs'],
            ['value' => '🧭', 'label' => 'Compass'],
            ['value' => '⏱', 'label' => 'Stopwatch'],
            ['value' => '⏲', 'label' => 'Timer Clock'],
            ['value' => '⏰', 'label' => 'Alarm Clock'],
            ['value' => '🕰', 'label' => 'Mantelpiece Clock'],
            ['value' => '⌛️', 'label' => 'Hourglass Done'],
            ['value' => '⏳', 'label' => 'Hourglass Not Done'],
            ['value' => '📡', 'label' => 'Antenna with Bars'],
            ['value' => '🔋', 'label' => 'Battery'],
            ['value' => '🪫', 'label' => 'Low Battery'],
            ['value' => '🔌', 'label' => 'Electric Plug'],
            ['value' => '💡', 'label' => 'Light Bulb'],
            ['value' => '🔦', 'label' => 'Flashlight'],
            ['value' => '🕯', 'label' => 'Candle'],
            ['value' => '🪔', 'label' => 'Diya Lamp'],
            ['value' => '🧯', 'label' => 'Fire Extinguisher'],
            ['value' => '🛢', 'label' => 'Oil Drum'],
            ['value' => '🛍️', 'label' => 'Shopping Bags'],
            ['value' => '💸', 'label' => 'Money with Wings'],
            ['value' => '💵', 'label' => 'Banknote with Dollar Sign'],
            ['value' => '💴', 'label' => 'Banknote with Yen Sign'],
            ['value' => '💶', 'label' => 'Banknote with Euro Sign'],
            ['value' => '💷', 'label' => 'Banknote with Pound Sign'],
            ['value' => '🪙', 'label' => 'Coin'],
            ['value' => '💰', 'label' => 'Money Bag'],
            ['value' => '💳', 'label' => 'Credit Card'],
            ['value' => '💎', 'label' => 'Gem Stone'],
            ['value' => '⚖️', 'label' => 'Balance Scale'],
            ['value' => '🪮', 'label' => 'Comb'],
            ['value' => '🪜', 'label' => 'Ladder'],
            ['value' => '🧰', 'label' => 'Toolbox'],
            ['value' => '🪛', 'label' => 'Screwdriver'],
            ['value' => '🔧', 'label' => 'Wrench'],
            ['value' => '🔨', 'label' => 'Hammer'],
            ['value' => '⚒', 'label' => 'Hammer and Pick'],
            ['value' => '🛠', 'label' => 'Hammer and Wrench'],
            ['value' => '⛏', 'label' => 'Pick'],
            ['value' => '🪚', 'label' => 'Saw'],
            ['value' => '🔩', 'label' => 'Nut and Bolt'],
            ['value' => '⚙️', 'label' => 'Gear'],
            ['value' => '🪤', 'label' => 'Mouse Trap'],
            ['value' => '🧱', 'label' => 'Brick'],
            ['value' => '⛓', 'label' => 'Chains'],
            ['value' => '⛓️‍💥', 'label' => 'Chains and Explosion'],
            ['value' => '🧲', 'label' => 'Magnet'],
            ['value' => '🔫', 'label' => 'Pistol'],
            ['value' => '💣', 'label' => 'Bomb'],
            ['value' => '🧨', 'label' => 'Firecracker'],
            ['value' => '🪓', 'label' => 'Axe'],
            ['value' => '🔪', 'label' => 'Knife'],
            ['value' => '🗡', 'label' => 'Dagger'],
            ['value' => '⚔️', 'label' => 'Crossed Swords'],
            ['value' => '🛡', 'label' => 'Shield'],
            ['value' => '🚬', 'label' => 'Cigarette'],
            ['value' => '⚰️', 'label' => 'Coffin'],
            ['value' => '🪦', 'label' => 'Headstone'],
            ['value' => '⚱️', 'label' => 'Funeral Urn'],
            ['value' => '🏺', 'label' => 'Amphora'],
            ['value' => '🔮', 'label' => 'Crystal Ball'],
            ['value' => '📿', 'label' => 'Prayer Beads'],
            ['value' => '🧿', 'label' => 'Nazar Amulet'],
            ['value' => '🪬', 'label' => 'Hamsa'],
            ['value' => '💈', 'label' => 'Barber Pole'],
            ['value' => '⚗️', 'label' => 'Alembic'],
            ['value' => '🔭', 'label' => 'Telescope'],
            ['value' => '🔬', 'label' => 'Microscope'],
            ['value' => '🕳', 'label' => 'Hole'],
            ['value' => '🩹', 'label' => 'Adhesive Bandage'],
            ['value' => '🩺', 'label' => 'Stethoscope'],
            ['value' => '🩻', 'label' => 'X-Ray'],
            ['value' => '🩼', 'label' => 'Bandage'],
            ['value' => '💊', 'label' => 'Pill'],
            ['value' => '💉', 'label' => 'Syringe'],
            ['value' => '🩸', 'label' => 'Drop of Blood'],
            ['value' => '🧬', 'label' => 'DNA'],
            ['value' => '🦠', 'label' => 'Lung'],
            ['value' => '🧫', 'label' => 'Petri Dish'],
            ['value' => '🧪', 'label' => 'Test Tube'],
            ['value' => '🌡', 'label' => 'Thermometer'],
            ['value' => '🧹', 'label' => 'Broom'],
            ['value' => '🪠', 'label' => 'Plunger'],
            ['value' => '🧺', 'label' => 'Basket'],
            ['value' => '🧻', 'label' => 'Toilet Paper'],
            ['value' => '🚽', 'label' => 'Toilet'],
            ['value' => '🚰', 'label' => 'Potable Water'],
            ['value' => '🚿', 'label' => 'Shower'],
            ['value' => '🛁', 'label' => 'Bath'],
            ['value' => '🛀', 'label' => 'Person Taking Bath'],
            ['value' => '🧼', 'label' => 'Soap'],
            ['value' => '🪥', 'label' => 'Toothbrush'],
            ['value' => '🪒', 'label' => 'Razor'],
            ['value' => '🧽', 'label' => 'Sponge'],
            ['value' => '🪣', 'label' => 'Bucket'],
            ['value' => '🧴', 'label' => 'Spray Bottle'],
            ['value' => '🛎', 'label' => 'Bellhop Bell'],
            ['value' => '🔑', 'label' => 'Key'],
            ['value' => '🗝', 'label' => 'Old Key'],
            ['value' => '🚪', 'label' => 'Door'],
            ['value' => '🪑', 'label' => 'Chair'],
            ['value' => '🛋', 'label' => 'Couch and Lamp'],
            ['value' => '🛏', 'label' => 'Bed'],
            ['value' => '🛌', 'label' => 'Person in Bed'],
            ['value' => '🧸', 'label' => 'Teddy Bear'],
            ['value' => '🪆', 'label' => 'Matryoshka Doll'],
            ['value' => '🖼', 'label' => 'Framed Picture'],
            ['value' => '🪞', 'label' => 'Mirror'],
            ['value' => '🪟', 'label' => 'Window'],
            ['value' => '🛍', 'label' => 'Shopping Bag'],
            ['value' => '🛒', 'label' => 'Shopping Cart'],
            ['value' => '🎁', 'label' => 'Gift'],
            ['value' => '🎈', 'label' => 'Balloon'],
            ['value' => '🎏', 'label' => 'Carp Streamer'],
            ['value' => '🎀', 'label' => 'Ribbon'],
            ['value' => '🪄', 'label' => 'Magic Wand'],
            ['value' => '🪅', 'label' => 'Piñata'],
            ['value' => '🎊', 'label' => 'Confetti Ball'],
            ['value' => '🎉', 'label' => 'Party Popper'],
            ['value' => '🪩', 'label' => 'Confetti'],
            ['value' => '🎎', 'label' => 'Dolls'],
            ['value' => '🏮', 'label' => 'Red Paper Lantern'],
            ['value' => '🎐', 'label' => 'Wind Chime'],
            ['value' => '🧧', 'label' => 'Red Envelope'],
            ['value' => '✉️', 'label' => 'Envelope'],
            ['value' => '📩', 'label' => 'Envelope with Arrow'],
            ['value' => '📨', 'label' => 'Incoming Envelope'],
            ['value' => '📧', 'label' => 'E-Mail'],
            ['value' => '💌', 'label' => 'Love Letter'],
            ['value' => '📥', 'label' => 'Inbox Tray'],
            ['value' => '📤', 'label' => 'Outbox Tray'],
            ['value' => '📦', 'label' => 'Package'],
            ['value' => '🏷', 'label' => 'Label'],
            ['value' => '🪧', 'label' => 'Identification Card'],
            ['value' => '📪', 'label' => 'Postbox'],
            ['value' => '📫', 'label' => 'Mailbox Closed'],
            ['value' => '📬', 'label' => 'Mailbox with Raised Flag'],
            ['value' => '📭', 'label' => 'Mailbox with Lowered Flag'],
            ['value' => '📮', 'label' => 'Postbox'],
            ['value' => '📯', 'label' => 'Postal Horn'],
            ['value' => '📜', 'label' => 'Scroll'],
            ['value' => '📃', 'label' => 'Page with Curl'],
            ['value' => '📄', 'label' => 'Page Facing Up'],
            ['value' => '📑', 'label' => 'Bookmark Tabs'],
            ['value' => '🧾', 'label' => 'Receipt'],
            ['value' => '📊', 'label' => 'Bar Chart'],
            ['value' => '📈', 'label' => 'Chart Increasing'],
            ['value' => '📉', 'label' => 'Chart Decreasing'],
            ['value' => '🗒', 'label' => 'Spiral Notepad'],
            ['value' => '🗓', 'label' => 'Spiral Calendar'],
            ['value' => '📆', 'label' => 'Calendar'],
            ['value' => '📅', 'label' => 'Tear-Off Calendar'],
            ['value' => '🗑', 'label' => 'Wastebasket'],
            ['value' => '🪪', 'label' => 'ID Card'],
            ['value' => '📇', 'label' => 'Card Index'],
            ['value' => '🗃', 'label' => 'Card File Box'],
            ['value' => '🗳', 'label' => 'Ballot Box'],
            ['value' => '🗄', 'label' => 'File Cabinet'],
            ['value' => '📋', 'label' => 'Clipboard'],
            ['value' => '📁', 'label' => 'File Folder'],
            ['value' => '📂', 'label' => 'Open File Folder'],
            ['value' => '🗂', 'label' => 'Card Index Dividers'],
            ['value' => '🗞', 'label' => 'Rolled-Up Newspaper'],
            ['value' => '📰', 'label' => 'Newspaper'],
            ['value' => '📓', 'label' => 'Notebook with Decorative Cover'],
            ['value' => '📔', 'label' => 'Notebook'],
            ['value' => '📒', 'label' => 'Ledger'],
            ['value' => '📕', 'label' => 'Red Book'],
            ['value' => '📗', 'label' => 'Green Book'],
            ['value' => '📘', 'label' => 'Blue Book'],
            ['value' => '📙', 'label' => 'Orange Book'],
            ['value' => '📚', 'label' => 'Books'],
            ['value' => '📖', 'label' => 'Open Book'],
            ['value' => '🔖', 'label' => 'Bookmark'],
            ['value' => '🧷', 'label' => 'Safety Pin'],
            ['value' => '🔗', 'label' => 'Link'],
            ['value' => '📎', 'label' => 'Paperclip'],
            ['value' => '🖇', 'label' => 'Linked Paperclips'],
            ['value' => '📐', 'label' => 'Triangular Ruler'],
            ['value' => '📏', 'label' => 'Straight Ruler'],
            ['value' => '🧮', 'label' => 'Abacus'],
            ['value' => '📌', 'label' => 'Pushpin'],
            ['value' => '📍', 'label' => 'Round Pushpin'],
            ['value' => '✂️', 'label' => 'Scissors'],
            ['value' => '🖊', 'label' => 'Pen'],
            ['value' => '🖋', 'label' => 'Fountain Pen'],
            ['value' => '✒️', 'label' => 'Black Nib'],
            ['value' => '🖌', 'label' => 'Paintbrush'],
            ['value' => '🖍', 'label' => 'Crayon'],
            ['value' => '📝', 'label' => 'Memo'],
            ['value' => '✏️', 'label' => 'Pencil'],
            ['value' => '🔍', 'label' => 'Magnifying Glass Tilted Left'],
            ['value' => '🔎', 'label' => 'Magnifying Glass Tilted Right'],
            ['value' => '🔏', 'label' => 'Locked with Key'],
            ['value' => '🔐', 'label' => 'Locked'],
            ['value' => '🔒', 'label' => 'Lock'],
            ['value' => '🔓', 'label' => 'Unlocked'],
            ['value' => '❤️', 'label' => 'Red Heart'],
            ['value' => '🩷', 'label' => 'Pink Heart'],
            ['value' => '🧡', 'label' => 'Orange Heart'],
            ['value' => '💛', 'label' => 'Yellow Heart'],
            ['value' => '💚', 'label' => 'Green Heart'],
            ['value' => '💙', 'label' => 'Blue Heart'],
            ['value' => '🩵', 'label' => 'Light Blue Heart'],
            ['value' => '💜', 'label' => 'Purple Heart'],
            ['value' => '🖤', 'label' => 'Black Heart'],
            ['value' => '🩶', 'label' => 'Gray Heart'],
            ['value' => '🤍', 'label' => 'White Heart'],
            ['value' => '🤎', 'label' => 'Brown Heart'],
            ['value' => '❤️‍🔥', 'label' => 'Heart on Fire'],
            ['value' => '❤️‍🩹', 'label' => 'Heart Hands'],
            ['value' => '💔', 'label' => 'Broken Heart'],
            ['value' => '❣️', 'label' => 'Exclamation Heart'],
            ['value' => '💕', 'label' => 'Two Hearts'],
            ['value' => '💞', 'label' => 'Revolving Hearts'],
            ['value' => '💓', 'label' => 'Beating Heart'],
            ['value' => '💗', 'label' => 'Growing Heart'],
            ['value' => '💖', 'label' => 'Sparkling Heart'],
            ['value' => '💘', 'label' => 'Heart with Arrow'],
            ['value' => '💝', 'label' => 'Heart with Ribbon'],
            ['value' => '💟', 'label' => 'Heart Decoration'],
            ['value' => '☮️', 'label' => 'Peace Symbol'],
            ['value' => '✝️', 'label' => 'Cross'],
            ['value' => '☪️', 'label' => 'Star and Crescent'],
            ['value' => '🪯', 'label' => 'Prayer Beads'],
            ['value' => '🕉', 'label' => 'Om Symbol'],
            ['value' => '☸️', 'label' => 'Wheel of Dharma'],
            ['value' => '✡️', 'label' => 'Star of David'],
            ['value' => '🔯', 'label' => 'Dotted Star'],
            ['value' => '🕎', 'label' => 'Menorah'],
            ['value' => '☯️', 'label' => 'Yin Yang'],
            ['value' => '☦️', 'label' => 'Orthodox Cross'],
            ['value' => '🛐', 'label' => 'Place of Worship'],
            ['value' => '⛎', 'label' => 'Ophiuchus'],
            ['value' => '♈️', 'label' => 'Aries'],
            ['value' => '♉️', 'label' => 'Taurus'],
            ['value' => '♊️', 'label' => 'Gemini'],
            ['value' => '♋️', 'label' => 'Cancer'],
            ['value' => '♌️', 'label' => 'Leo'],
            ['value' => '♍️', 'label' => 'Virgo'],
            ['value' => '♎️', 'label' => 'Libra'],
            ['value' => '♏️', 'label' => 'Scorpio'],
            ['value' => '♐️', 'label' => 'Sagittarius'],
            ['value' => '♑️', 'label' => 'Capricorn'],
            ['value' => '♒️', 'label' => 'Aquarius'],
            ['value' => '♓️', 'label' => 'Pisces'],
            ['value' => '🆔', 'label' => 'ID Button'],
            ['value' => '⚛️', 'label' => 'Atom Symbol'],
            ['value' => '🉑', 'label' => 'Japanese Acceptable Button'],
            ['value' => '☢️', 'label' => 'Radioactive Sign'],
            ['value' => '☣️', 'label' => 'Biohazard Sign'],
            ['value' => '📴', 'label' => 'Mobile Phone Off'],
            ['value' => '📳', 'label' => 'Vibration Mode'],
            ['value' => '🈶', 'label' => 'Japanese “Not Free of Charge” Button'],
            ['value' => '🈚️', 'label' => 'Japanese “Free of Charge” Button'],
            ['value' => '🈸', 'label' => 'Japanese “Application” Button'],
            ['value' => '🈺', 'label' => 'Japanese “Open for Business” Button'],
            ['value' => '🈷️', 'label' => 'Japanese “Monthly Amount” Button'],
            ['value' => '✴️', 'label' => 'Eight-Spoked Asterisk'],
            ['value' => '🆚', 'label' => 'VS Button'],
            ['value' => '💮', 'label' => 'White Flower'],
            ['value' => '🉐', 'label' => 'Japanese “Bunkasai” Button'],
            ['value' => '㊙️', 'label' => 'Japanese “Secret” Button'],
            ['value' => '㊗️', 'label' => 'Japanese “Congratulations” Button'],
            ['value' => '🈴', 'label' => 'Japanese “Passed” Button'],
            ['value' => '🈵', 'label' => 'Japanese “No Vacancy” Button'],
            ['value' => '🈹', 'label' => 'Japanese “Discount” Button'],
            ['value' => '🈲', 'label' => 'Japanese “Prohibited” Button'],
            ['value' => '🅰️', 'label' => 'A Button (Blood Type)'],
            ['value' => '🅱️', 'label' => 'B Button (Blood Type)'],
            ['value' => '🆎', 'label' => 'AB Button (Blood Type)'],
            ['value' => '🆑', 'label' => 'CL Button'],
            ['value' => '🅾️', 'label' => 'O Button (Blood Type)'],
            ['value' => '🆘', 'label' => 'SOS Button'],
            ['value' => '❌', 'label' => 'Cross Mark'],
            ['value' => '⭕️', 'label' => 'Red Circle'],
            ['value' => '🛑', 'label' => 'Stop Sign'],
            ['value' => '⛔️', 'label' => 'No Entry'],
            ['value' => '📛', 'label' => 'Name Badge'],
            ['value' => '🚫', 'label' => 'Prohibited'],
            ['value' => '💯', 'label' => 'Hundred Points'],
            ['value' => '💢', 'label' => 'Anger Symbol'],
            ['value' => '♨️', 'label' => 'Hot Springs'],
            ['value' => '🚷', 'label' => 'No Pedestrians'],
            ['value' => '🚯', 'label' => 'No Littering'],
            ['value' => '🚳', 'label' => 'No Bicycles'],
            ['value' => '🚱', 'label' => 'No Drinking'],
            ['value' => '🔞', 'label' => 'Age Restriction'],
            ['value' => '📵', 'label' => 'No Mobile Phones'],
            ['value' => '🚭', 'label' => 'No Smoking'],
            ['value' => '❗️', 'label' => 'Exclamation Mark'],
            ['value' => '❕', 'label' => 'White Exclamation Mark'],
            ['value' => '❓', 'label' => 'Question Mark'],
            ['value' => '❔', 'label' => 'White Question Mark'],
            ['value' => '‼️', 'label' => 'Double Exclamation Mark'],
            ['value' => '⁉️', 'label' => 'Exclamation Question Mark'],
            ['value' => '🔅', 'label' => 'Low Brightness'],
            ['value' => '🔆', 'label' => 'High Brightness'],
            ['value' => '〽️', 'label' => 'Part Alternation Mark'],
            ['value' => '⚠️', 'label' => 'Warning'],
            ['value' => '🚸', 'label' => 'Children Crossing'],
            ['value' => '🔱', 'label' => 'Trident Emblem'],
            ['value' => '⚜️', 'label' => 'Fleur-de-lis'],
            ['value' => '🔰', 'label' => 'Japanese “Beginner” Button'],
            ['value' => '♻️', 'label' => 'Recycling Symbol'],
            ['value' => '✅', 'label' => 'Check Mark Button'],
            ['value' => '🈯️', 'label' => 'Japanese “Reserved” Button'],
            ['value' => '💹', 'label' => 'Chart Increasing with Yen'],
            ['value' => '❇️', 'label' => 'Sparkle'],
            ['value' => '✳️', 'label' => 'Eight-Pointed Star'],
            ['value' => '❎', 'label' => 'Negative Squared Cross Mark'],
            ['value' => '🌐', 'label' => 'Globe with Meridians'],
            ['value' => '💠', 'label' => 'Diamond with a Dot'],
            ['value' => 'Ⓜ️', 'label' => 'Circled M'],
            ['value' => '🌀', 'label' => 'Cyclone'],
            ['value' => '💤', 'label' => 'Sleeping Symbol'],
            ['value' => '🏧', 'label' => 'ATM Sign'],
            ['value' => '🚾', 'label' => 'Wc'],
            ['value' => '♿️', 'label' => 'Wheelchair Symbol'],
            ['value' => '🅿️', 'label' => 'Parking'],
            ['value' => '🛗', 'label' => 'Elevator'],
            ['value' => '🈳', 'label' => 'Japanese “Vacancy” Button'],
            ['value' => '🈂️', 'label' => 'Japanese “Service Charge” Button'],
            ['value' => '🛂', 'label' => 'Customs'],
            ['value' => '🛃', 'label' => 'Passport Control'],
            ['value' => '🛄', 'label' => 'Baggage Claim'],
            ['value' => '🛅', 'label' => 'Left Luggage'],
            ['value' => '🚹', 'label' => 'Men’s Room'],
            ['value' => '🚺', 'label' => 'Women’s Room'],
            ['value' => '🚼', 'label' => 'Baby Symbol'],
            ['value' => '⚧', 'label' => 'Transgender Symbol'],
            ['value' => '🚻', 'label' => 'Restroom'],
            ['value' => '🚮', 'label' => 'Litter in Bin Sign'],
            ['value' => '🎦', 'label' => 'Cinema'],
            ['value' => '🛜', 'label' => 'Antenna Bars'],
            ['value' => '📶', 'label' => 'Antenna with Bars'],
            ['value' => '🈁', 'label' => 'Japanese “Available” Button'],
            ['value' => '🔣', 'label' => 'Input Symbols'],
            ['value' => 'ℹ️', 'label' => 'Information'],
            ['value' => '🔤', 'label' => 'Input Latin Letters'],
            ['value' => '🔡', 'label' => 'Input Latin Letters'],
            ['value' => '🔠', 'label' => 'Input Latin Letters'],
            ['value' => '🆖', 'label' => 'NG Button'],
            ['value' => '🆗', 'label' => 'OK Button'],
            ['value' => '🆙', 'label' => 'Up! Button'],
            ['value' => '🆒', 'label' => 'Cool Button'],
            ['value' => '🆕', 'label' => 'New Button'],
            ['value' => '🆓', 'label' => 'Free Button'],
            ['value' => '0️⃣', 'label' => 'Keycap 0'],
            ['value' => '1️⃣', 'label' => 'Keycap 1'],
            ['value' => '2️⃣', 'label' => 'Keycap 2'],
            ['value' => '3️⃣', 'label' => 'Keycap 3'],
            ['value' => '4️⃣', 'label' => 'Keycap 4'],
            ['value' => '5️⃣', 'label' => 'Keycap 5'],
            ['value' => '6️⃣', 'label' => 'Keycap 6'],
            ['value' => '7️⃣', 'label' => 'Keycap 7'],
            ['value' => '8️⃣', 'label' => 'Keycap 8'],
            ['value' => '9️⃣', 'label' => 'Keycap 9'],
            ['value' => '🔟', 'label' => 'Keycap 10'],
            ['value' => '🔢', 'label' => 'Input Numbers'],
            ['value' => '#️⃣', 'label' => 'Keycap #'],
            ['value' => '*️⃣', 'label' => 'Keycap *'],
            ['value' => '⏏️', 'label' => 'Eject Button'],
            ['value' => '▶️', 'label' => 'Play Button'],
            ['value' => '⏸', 'label' => 'Pause Button'],
            ['value' => '⏯', 'label' => 'Play/Pause Button'],
            ['value' => '⏹', 'label' => 'Stop Button'],
            ['value' => '⏺', 'label' => 'Record Button'],
            ['value' => '⏭', 'label' => 'Next Track Button'],
            ['value' => '⏮', 'label' => 'Previous Track Button'],
            ['value' => '⏩', 'label' => 'Fast Forward Button'],
            ['value' => '⏪', 'label' => 'Rewind Button'],
            ['value' => '⏫', 'label' => 'Fast Up Button'],
            ['value' => '⏬', 'label' => 'Fast Down Button'],
            ['value' => '◀️', 'label' => 'Back Arrow'],
            ['value' => '🔼', 'label' => 'Upwards Button'],
            ['value' => '🔽', 'label' => 'Downwards Button'],
            ['value' => '➡️', 'label' => 'Right Arrow'],
            ['value' => '⬅️', 'label' => 'Left Arrow'],
            ['value' => '⬆️', 'label' => 'Up Arrow'],
            ['value' => '⬇️', 'label' => 'Down Arrow'],
            ['value' => '↗️', 'label' => 'Up-Right Arrow'],
            ['value' => '↘️', 'label' => 'Down-Right Arrow'],
            ['value' => '↙️', 'label' => 'Down-Left Arrow'],
            ['value' => '↖️', 'label' => 'Up-Left Arrow'],
            ['value' => '↕️', 'label' => 'Up-Down Arrow'],
            ['value' => '↔️', 'label' => 'Left-Right Arrow'],
            ['value' => '↪️', 'label' => 'Right Arrow Curving Left'],
            ['value' => '↩️', 'label' => 'Right Arrow Curving Right'],
            ['value' => '⤴️', 'label' => 'Arrow Heading Upwards'],
            ['value' => '⤵️', 'label' => 'Arrow Heading Downwards'],
            ['value' => '🔀', 'label' => 'Shuffle Tracks Button'],
            ['value' => '🔁', 'label' => 'Repeat Button'],
            ['value' => '🔂', 'label' => 'Repeat One Button'],
            ['value' => '🔄', 'label' => 'Repeat Button'],
            ['value' => '🔃', 'label' => 'Clockwise Vertical Arrows'],
            ['value' => '🎵', 'label' => 'Musical Note'],
            ['value' => '🎶', 'label' => 'Musical Notes'],
            ['value' => '➕', 'label' => 'Plus Sign'],
            ['value' => '➖', 'label' => 'Minus Sign'],
            ['value' => '➗', 'label' => 'Division Sign'],
            ['value' => '✖️', 'label' => 'Multiplication Sign'],
            ['value' => '🟰', 'label' => 'Keycap 0'],
            ['value' => '♾', 'label' => 'Infinity'],
            ['value' => '💲', 'label' => 'Dollar Sign'],
            ['value' => '💱', 'label' => 'Currency Exchange'],
            ['value' => '™️', 'label' => 'Trade Mark'],
            ['value' => '©️', 'label' => 'Copyright'],
            ['value' => '®️', 'label' => 'Registered'],
            ['value' => '〰️', 'label' => 'Wavy Dash'],
            ['value' => '➰', 'label' => 'Curly Loop'],
            ['value' => '➿', 'label' => 'Double Curly Loop'],
            ['value' => '🔚', 'label' => 'End Arrow'],
            ['value' => '🔙', 'label' => 'Back Arrow'],
            ['value' => '🔛', 'label' => 'On! Arrow'],
            ['value' => '🔝', 'label' => 'Top Arrow'],
            ['value' => '🔜', 'label' => 'Soon Arrow'],
            ['value' => '✔️', 'label' => 'Check Mark'],
            ['value' => '☑️', 'label' => 'Ballot Box with Check'],
            ['value' => '🔘', 'label' => 'Radio Button'],
            ['value' => '🔴', 'label' => 'Red Circle'],
            ['value' => '🟠', 'label' => 'Orange Circle'],
            ['value' => '🟡', 'label' => 'Yellow Circle'],
            ['value' => '🟢', 'label' => 'Green Circle'],
            ['value' => '🔵', 'label' => 'Blue Circle'],
            ['value' => '🟣', 'label' => 'Purple Circle'],
            ['value' => '⚫️', 'label' => 'Black Circle'],
            ['value' => '⚪️', 'label' => 'White Circle'],
            ['value' => '🟤', 'label' => 'Brown Circle'],
            ['value' => '🔺', 'label' => 'Red Triangle Pointed Up'],
            ['value' => '🔻', 'label' => 'Red Triangle Pointed Down'],
            ['value' => '🔸', 'label' => 'Orange Diamond'],
            ['value' => '🔹', 'label' => 'Blue Diamond'],
            ['value' => '🔶', 'label' => 'Large Orange Diamond'],
            ['value' => '🔷', 'label' => 'Large Blue Diamond'],
            ['value' => '🔳', 'label' => 'White Square Button'],
            ['value' => '🔲', 'label' => 'Black Square Button'],
            ['value' => '▪️', 'label' => 'Small Black Square'],
            ['value' => '▫️', 'label' => 'Small White Square'],
            ['value' => '◾️', 'label' => 'Medium Black Square'],
            ['value' => '◽️', 'label' => 'Medium White Square'],
            ['value' => '◼️', 'label' => 'Black Medium Square'],
            ['value' => '◻️', 'label' => 'White Medium Square'],
            ['value' => '🟥', 'label' => 'Red Square'],
            ['value' => '🟧', 'label' => 'Orange Square'],
            ['value' => '🟨', 'label' => 'Yellow Square'],
            ['value' => '🟩', 'label' => 'Green Square'],
            ['value' => '🟦', 'label' => 'Blue Square'],
            ['value' => '🟪', 'label' => 'Purple Square'],
            ['value' => '⬛️', 'label' => 'Black Large Square'],
            ['value' => '⬜️', 'label' => 'White Large Square'],
            ['value' => '🟫', 'label' => 'Brown Square'],
            ['value' => '🔈', 'label' => 'Low Volume Speaker'],
            ['value' => '🔇', 'label' => 'Mute Speaker'],
            ['value' => '🔉', 'label' => 'Medium Volume Speaker'],
            ['value' => '🔊', 'label' => 'High Volume Speaker'],
            ['value' => '🔔', 'label' => 'Bell'],
            ['value' => '🔕', 'label' => 'Bell with Slash'],
            ['value' => '📣', 'label' => 'Public Address Loudspeaker'],
            ['value' => '📢', 'label' => 'Loudspeaker'],
            ['value' => '👁‍🗨', 'label' => 'Eye in Speech Bubble'],
            ['value' => '💬', 'label' => 'Speech Balloon'],
            ['value' => '💭', 'label' => 'Thought Balloon'],
            ['value' => '🗯', 'label' => 'Right Anger Bubble'],
            ['value' => '♠️', 'label' => 'Spade Suit'],
            ['value' => '♣️', 'label' => 'Club Suit'],
            ['value' => '♥️', 'label' => 'Heart Suit'],
            ['value' => '♦️', 'label' => 'Diamond Suit'],
            ['value' => '🃏', 'label' => 'Joker'],
            ['value' => '🎴', 'label' => 'Flower Playing Cards'],
            ['value' => '🀄️', 'label' => 'Mahjong Tile Red Dragon'],
            ['value' => '🕐', 'label' => 'Clock Face One O’Clock'],
            ['value' => '🕑', 'label' => 'Clock Face Two O’Clock'],
            ['value' => '🕒', 'label' => 'Clock Face Three O’Clock'],
            ['value' => '🕓', 'label' => 'Clock Face Four O’Clock'],
            ['value' => '🕔', 'label' => 'Clock Face Five O’Clock'],
            ['value' => '🕕', 'label' => 'Clock Face Six O’Clock'],
            ['value' => '🕖', 'label' => 'Clock Face Seven O’Clock'],
            ['value' => '🕗', 'label' => 'Clock Face Eight O’Clock'],
            ['value' => '🕘', 'label' => 'Clock Face Nine O’Clock'],
            ['value' => '🕙', 'label' => 'Clock Face Ten O’Clock'],
            ['value' => '🕚', 'label' => 'Clock Face Eleven O’Clock'],
            ['value' => '🕛', 'label' => 'Clock Face Twelve O’Clock'],
            ['value' => '🕜', 'label' => 'Clock Face One-Thirty'],
            ['value' => '🕝', 'label' => 'Clock Face Two-Thirty'],
            ['value' => '🕞', 'label' => 'Clock Face Three-Thirty'],
            ['value' => '🕟', 'label' => 'Clock Face Four-Thirty'],
            ['value' => '🕠', 'label' => 'Clock Face Five-Thirty'],
            ['value' => '🕡', 'label' => 'Clock Face Six-Thirty'],
            ['value' => '🕢', 'label' => 'Clock Face Seven-Thirty'],
            ['value' => '🕣', 'label' => 'Clock Face Eight-Thirty'],
            ['value' => '🕤', 'label' => 'Clock Face Nine-Thirty'],
            ['value' => '🕥', 'label' => 'Clock Face Ten-Thirty'],
            ['value' => '🕦', 'label' => 'Clock Face Eleven-Thirty'],
            ['value' => '🕧', 'label' => 'Clock Face Twelve-Thirty'],
            ['value' => '✢', 'label' => 'Four Pointed Star'],
            ['value' => '✣', 'label' => 'Eight Pointed Star'],
            ['value' => '✤', 'label' => 'Four Pointed Star with Middle Dot'],
            ['value' => '✥', 'label' => 'White Star'],
            ['value' => '✦', 'label' => 'Black Star'],
            ['value' => '✧', 'label' => 'Star with a White Center'],
            ['value' => '★', 'label' => 'Black Star'],
            ['value' => '☆', 'label' => 'White Star'],
            ['value' => '✯', 'label' => 'Star of David'],
            ['value' => '✡︎', 'label' => 'Star of David'],
            ['value' => '✩', 'label' => 'Star'],
            ['value' => '✪', 'label' => 'Star with Right Half Black'],
            ['value' => '✫', 'label' => 'Star with Left Half Black'],
            ['value' => '✬', 'label' => 'Star with Upper Right Black Triangle'],
            ['value' => '✭', 'label' => 'Star with Upper Left Black Triangle'],
            ['value' => '✮', 'label' => 'Star with Lower Right Black Triangle'],
            ['value' => '✶', 'label' => 'White Star'],
            ['value' => '✷', 'label' => 'Black Star'],
            ['value' => '✵', 'label' => 'Star with Upper Triangle'],
            ['value' => '✸', 'label' => 'Star with Lower Triangle'],
            ['value' => '✹', 'label' => 'Star with Left Triangle'],
            ['value' => '→', 'label' => 'Right Arrow'],
            ['value' => '⇒', 'label' => 'Right Double Arrow'],
            ['value' => '⟹', 'label' => 'Long Right Arrow'],
            ['value' => '⇨', 'label' => 'Right Arrow with Tip Downwards'],
            ['value' => '⇾', 'label' => 'Right Arrow with Tip Upwards'],
            ['value' => '➾', 'label' => 'Right Arrow Curving Downwards'],
            ['value' => '⇢', 'label' => 'Right Arrow Curving Upwards'],
            ['value' => '☛', 'label' => 'Black Right Pointing Index'],
            ['value' => '☞', 'label' => 'White Right Pointing Index'],
            ['value' => '➔', 'label' => 'Right Arrow with Curved End'],
            ['value' => '➜', 'label' => 'Right Arrow with Loop'],
            ['value' => '➙', 'label' => 'Right Arrow with Curve and Circle'],
            ['value' => '➛', 'label' => 'Right Arrow with Hook'],
            ['value' => '➝', 'label' => 'Right Arrow with Extended Tail'],
            ['value' => '➞', 'label' => 'Right Arrow with Circle End'],
            ['value' => '♠︎', 'label' => 'Black Spade Suit'],
            ['value' => '♣︎', 'label' => 'Black Club Suit'],
            ['value' => '♥︎', 'label' => 'Black Heart Suit'],
            ['value' => '♦︎', 'label' => 'Black Diamond Suit'],
            ['value' => '♤', 'label' => 'White Spade Suit'],
            ['value' => '♧', 'label' => 'White Club Suit'],
            ['value' => '♡', 'label' => 'White Heart Suit'],
            ['value' => '♢', 'label' => 'White Diamond Suit'],
            ['value' => '♚', 'label' => 'Black King Chess Piece'],
            ['value' => '♛', 'label' => 'Black Queen Chess Piece'],
            ['value' => '♜', 'label' => 'Black Rook'],
            ['value' => '♝', 'label' => 'Black Bishop'],
            ['value' => '♞', 'label' => 'Black Knight'],
            ['value' => '♟', 'label' => 'Black Pawn'],
            ['value' => '♔', 'label' => 'White King'],
            ['value' => '♕', 'label' => 'White Queen'],
            ['value' => '♖', 'label' => 'White Rook'],
            ['value' => '♗', 'label' => 'White Bishop'],
            ['value' => '♘', 'label' => 'White Knight'],
            ['value' => '♙', 'label' => 'White Pawn'],
            ['value' => '⚀', 'label' => 'Die Face-1'],
            ['value' => '⚁', 'label' => 'Die Face-2'],
            ['value' => '⚂', 'label' => 'Die Face-3'],
            ['value' => '⚃', 'label' => 'Die Face-4'],
            ['value' => '⚄', 'label' => 'Die Face-5'],
            ['value' => '⚅', 'label' => 'Die Face-6'],
            ['value' => '🂠', 'label' => 'Playing Card Back'],
            ['value' => '⚈', 'label' => 'Die Face-1 Dot'],
            ['value' => '⚉', 'label' => 'Die Face-2 Dots'],
            ['value' => '⚆', 'label' => 'Die Face-3 Dots'],
            ['value' => '⚇', 'label' => 'Die Face-4 Dots'],
            ['value' => '𓀀', 'label' => 'Egyptian Hieroglyph A001'],
            ['value' => '𓀁', 'label' => 'Egyptian Hieroglyph A002'],
            ['value' => '𓀂', 'label' => 'Egyptian Hieroglyph A003'],
            ['value' => '𓀃', 'label' => 'Egyptian Hieroglyph A004'],
            ['value' => '𓀄', 'label' => 'Egyptian Hieroglyph A005'],
            ['value' => '𓀅', 'label' => 'Egyptian Hieroglyph A006'],
            ['value' => '𓀆', 'label' => 'Egyptian Hieroglyph A007'],
            ['value' => '𓀇', 'label' => 'Egyptian Hieroglyph A008'],
            ['value' => '𓀈', 'label' => 'Egyptian Hieroglyph A009'],
            ['value' => '𓀉', 'label' => 'Egyptian Hieroglyph A010'],
            ['value' => '𓀊', 'label' => 'Egyptian Hieroglyph A011'],
            ['value' => '𓀋', 'label' => 'Egyptian Hieroglyph A012'],
            ['value' => '𓀌', 'label' => 'Egyptian Hieroglyph A013'],
            ['value' => '𓀍', 'label' => 'Egyptian Hieroglyph A014'],
            ['value' => '𓀎', 'label' => 'Egyptian Hieroglyph A015'],
            ['value' => '𓀏', 'label' => 'Egyptian Hieroglyph A016'],
            ['value' => '𓀐', 'label' => 'Egyptian Hieroglyph A017'],
            ['value' => '𓀑', 'label' => 'Egyptian Hieroglyph A018'],
            ['value' => '𓀒', 'label' => 'Egyptian Hieroglyph A019'],
            ['value' => '𓀓', 'label' => 'Egyptian Hieroglyph A020'],
            ['value' => '𓀔', 'label' => 'Egyptian Hieroglyph A021'],
            ['value' => '𓀕', 'label' => 'Egyptian Hieroglyph A022'],
            ['value' => '𓀖', 'label' => 'Egyptian Hieroglyph A023'],
            ['value' => '𓀗', 'label' => 'Egyptian Hieroglyph A024'],
            ['value' => '𓀘', 'label' => 'Egyptian Hieroglyph A025'],
            ['value' => '𓀙', 'label' => 'Egyptian Hieroglyph A026'],
            ['value' => '𓀚', 'label' => 'Egyptian Hieroglyph A027'],
            ['value' => '𓀛', 'label' => 'Egyptian Hieroglyph A028'],
            ['value' => '𓀜', 'label' => 'Egyptian Hieroglyph A029'],
            ['value' => '𓀝', 'label' => 'Egyptian Hieroglyph A030'],
        ];

        foreach ($emojis as $emoji) {
            Emoji::create($emoji);
        }
    }
}
